version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:arm64v8-4.0.5
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      #- TRANSMISSION_WEB_HOME= #optional
      #- USER= #optional
      #- PASS= #optional
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - /storage/data/transmission/config:/config
      - /var/media/PINXITO/transmission_downloads:/downloads
      - /var/media/PINXITO/transmission_watch_folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=es
      - WG_HOST=XXXXXXXXXXX.noip.me
      - PASSWORD=XXXXXXXXXXXXXXXXXX
      - WG_PORT=51820
      
      # Optional:
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true 
    volumes:
      - /storage/data/wireguard/config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  teamspeak:
    image: ertagh/teamspeak3-server:latest-box
    container_name: teamspeak
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TIME_ZONE=Europe/Madrid
      - TS_UPDATE=1
    volumes:
      - /storage/data/teamspeak/save/:/teamspeak/save/ 
    restart: unless-stopped
